// <auto-generated />
using BankManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace BankManager.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("BankManager.Data.Entity.AccountEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName");

                    b.Property<string>("AccountNumber");

                    b.Property<bool>("Active");

                    b.Property<string>("BankName");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Account");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AccountEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.PortfolioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName");

                    b.Property<bool>("Active");

                    b.Property<string>("BankName");

                    b.Property<string>("PortfolioNumber");

                    b.HasKey("Id");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("BankManager.Data.Entity.PortfolioGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedIsinList");

                    b.Property<bool>("IncludeInCalculations");

                    b.Property<string>("Name");

                    b.Property<decimal>("TargetPercentage");

                    b.HasKey("Id");

                    b.ToTable("PortfolioGroup");
                });

            modelBuilder.Entity("BankManager.Data.Entity.PositionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<decimal>("CurrentValue");

                    b.Property<string>("CurrentValueCurrencyIso");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Isin");

                    b.Property<string>("Name");

                    b.Property<decimal>("OriginalValue");

                    b.Property<string>("OriginalValueCurrencyIso");

                    b.Property<long?>("PortfolioId");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Position");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PositionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.TransactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AccountId");

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("AvailabilityDate");

                    b.Property<string>("CurrencyIso");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<DateTime>("PostingDate");

                    b.Property<string>("Text");

                    b.Property<int?>("UniqueId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transaction");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankAccountEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.AccountEntity");

                    b.Property<string>("Iban");

                    b.ToTable("Account");

                    b.HasDiscriminator().HasValue("BankAccountEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.CreditCardEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.AccountEntity");

                    b.Property<string>("CreditCardNumber");

                    b.ToTable("Account");

                    b.HasDiscriminator().HasValue("CreditCardEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.FlatexPositionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.PositionEntity");

                    b.Property<string>("Category");

                    b.Property<string>("Depository");

                    b.Property<string>("StockExchange");

                    b.ToTable("Position");

                    b.HasDiscriminator().HasValue("FlatexPositionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.RaiffeisenPositionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.PositionEntity");


                    b.ToTable("Position");

                    b.HasDiscriminator().HasValue("RaiffeisenPositionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.SalePositionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.PositionEntity");


                    b.ToTable("Position");

                    b.HasDiscriminator().HasValue("SalePositionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.DkbTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionEntity");

                    b.Property<string>("CreditorId");

                    b.Property<string>("CustomerReference");

                    b.Property<string>("MandateReference");

                    b.Property<string>("OtherBic");

                    b.Property<string>("OtherIban");

                    b.Property<string>("PostingText");

                    b.Property<string>("SenderReceiver");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("DkbTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.FlatexTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionEntity");

                    b.Property<string>("Bic");

                    b.Property<string>("Iban");

                    b.Property<string>("TransactionNumber");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("FlatexTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.RaiffeisenTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionEntity");


                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("RaiffeisenTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.RciTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionEntity");

                    b.Property<string>("ReasonForTransfer");

                    b.Property<string>("StatementNumber");

                    b.Property<string>("TransferDetail");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("RciTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.SollHabenTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionEntity");

                    b.Property<decimal>("Haben");

                    b.Property<decimal>("Soll");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("SollHabenTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.TransactionForeignCurrencyEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionEntity");

                    b.Property<decimal>("AmountForeignCurrency");

                    b.Property<decimal>("ExchangeRate");

                    b.Property<string>("ForeignCurrencyIso");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("TransactionForeignCurrencyEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.DkbCreditTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionForeignCurrencyEntity");


                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("DkbCreditTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.Number26TransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionForeignCurrencyEntity");

                    b.Property<string>("Category");

                    b.Property<string>("Payee");

                    b.Property<string>("PayeeAccountNumber");

                    b.Property<string>("PaymentReference");

                    b.Property<string>("TransactionType");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("Number26TransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.BankTransactions.PayPalTransactionEntity", b =>
                {
                    b.HasBaseType("BankManager.Data.Entity.TransactionForeignCurrencyEntity");

                    b.Property<string>("FromEmailAddress");

                    b.Property<string>("InvoiceNumber");

                    b.Property<decimal>("NetAmount");

                    b.Property<string>("ReferenceTxnId");

                    b.Property<string>("ToEmailAddress");

                    b.Property<string>("TransactionId");

                    b.Property<string>("Type");

                    b.ToTable("Transaction");

                    b.HasDiscriminator().HasValue("PayPalTransactionEntity");
                });

            modelBuilder.Entity("BankManager.Data.Entity.PositionEntity", b =>
                {
                    b.HasOne("BankManager.Data.Entity.PortfolioEntity", "Portfolio")
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId");
                });

            modelBuilder.Entity("BankManager.Data.Entity.TransactionEntity", b =>
                {
                    b.HasOne("BankManager.Data.Entity.AccountEntity", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId");
                });
#pragma warning restore 612, 618
        }
    }
}
